apiVersion: v1
kind: Service
metadata:
  name: mock-was-server-svc-lb
spec:
  selector:
    app: mock-was-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer

